# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SQLApp', '0003_dojos_ninjas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo_id',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(default='NO DOJO', on_delete=django.db.models.deletion.CASCADE, related_name='dojo', to='SQLApp.Dojos'),
            preserve_default=False,
        ),
    ]
