# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQLApp', '0004_auto_20190912_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo',
        ),
    ]
