# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SQLApp', '0005_remove_ninjas_dojo'),
    ]

    operations = [
        migrations.CreateModel(
            name='dojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('assigned_dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_ninjas', to='SQLApp.dojo')),
            ],
        ),
        migrations.DeleteModel(
            name='Dojos',
        ),
        migrations.DeleteModel(
            name='Ninjas',
        ),
    ]
