# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQLApp', '0006_auto_20190912_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='oldDojo', max_length=600),
            preserve_default=False,
        ),
    ]
