# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegistrationApps', '0002_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posts',
            new_name='users',
        ),
    ]
