# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegistrationApps', '0003_auto_20190918_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='LoginRegistrationApps.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='LoginRegistrationApps.user'),
        ),
    ]
